#!/bin/bash

QMAKE=qmake-qt4
TAR=tar
LRELEASE=lrelease
NUM_CPUS=$(cat /proc/cpuinfo | grep processor | wc -l)

# Package naming

NAME=dustrac
VERSION=1.6.2
ARCH=linux-x86_64
QT=qt4

# Build

$QMAKE && make -j$NUM_CPUS || exit -1

# Update translations

$LRELEASE ./src/game/game.pro && $LRELEASE ./src/editor/editor.pro || exit -1

# Install to packaging dir

PACKAGE_PATH=$NAME-$VERSION-$ARCH-$QT
rm -rf $PACKAGE_PATH
mkdir $PACKAGE_PATH

mkdir -p data/translations
cp -v ./src/game/translations/*.qm data/translations   &&
cp -v ./src/editor/translations/*.qm data/translations &&
cp -v ./src/game/dustrac-game $PACKAGE_PATH            &&
cp -v ./src/editor/dustrac-editor $PACKAGE_PATH        &&
cp -rv data $PACKAGE_PATH                              || exit -1

TEXT_FILES="AUTHORS CHANGELOG COPYING README"
cp -v $TEXT_FILES $PACKAGE_PATH || exit -1

# Copy dependecies

cp -v $(ldd $PACKAGE_PATH/dustrac-game | grep "/usr/lib" | grep -v libX | grep -v fontconfig | grep -v gobject | awk '{print $3}') $PACKAGE_PATH

# Additional libs

LIBS=png
for lib in $LIBS; do
cp -v $(ldd $PACKAGE_PATH/$BIN | grep $lib | awk '{print $3}') $PACKAGE_PATH
done

# Copy needed Qt plugins

mkdir $PACKAGE_PATH/plugins
QT_PLUGIN_DIR=$($QMAKE -query | grep QT_INSTALL_PLUGINS | cut -d: -f2)
cp -r -v $QT_PLUGIN_DIR/imageformats $PACKAGE_PATH/plugins
cp -r -v $QT_PLUGIN_DIR/graphicssystems $PACKAGE_PATH/plugins

# Create qt.conf (this is needed for possible plugin conflicts)

QTCONF=$PACKAGE_PATH/qt.conf
echo "[Paths]" > $QTCONF
echo "Prefix  = ." >> $QTCONF
echo "Plugins = ./plugins" >> $QTCONF

# Create start script for the game

cp $PACKAGE_PATH/dustrac-game $PACKAGE_PATH/g.bin
SCRIPT=$PACKAGE_PATH/dustrac-game
echo "#!/bin/sh" > $SCRIPT
echo "LD_LIBRARY_PATH=. ./g.bin" >> $SCRIPT
chmod 755 $SCRIPT

# Create start script for the editor

cp $PACKAGE_PATH/dustrac-editor $PACKAGE_PATH/e.bin
SCRIPT=$PACKAGE_PATH/dustrac-editor
echo "#!/bin/sh" > $SCRIPT
echo "LD_LIBRARY_PATH=. ./e.bin" >> $SCRIPT
chmod 755 $SCRIPT

# Create tgz archive

TGZ_ARCHIVE=$PACKAGE_PATH.tar.gz
rm -f $TGZ_ARCHIVE
$TAR czvf $TGZ_ARCHIVE $PACKAGE_PATH

ls -ltr

echo "Done."

